name: Bug Report
description: Report something that's broken
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: markdown
  attributes:
#     label: Description
    value: What's broken? What were you expecting to happen?
  validations:
    required: true
- type: markdown
  attributes:
#     label: Steps to reproduce
    value: |
        1. Do this thing...
        2. Then do that thing...
        3. And finally, do something else...
- type: markdown
  attributes:
#     label: Environment
    value: Please copy the output of `php please support:details`
  validations:
    required: true
