name: '🐛  Bug Report'
description: Report something that's broken
body:
- type: textarea
  attributes:
    label: Description
    placeholder: What's broken? What were you expecting to happen?
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    placeholder: |
        1. Do this thing...
        2. Then do that thing...
        3. And finally, do something else...
- type: textarea
  attributes:
    label: Environment
    placeholder: Please copy the output of `php please support:details`
  validations:
    required: true
