name: Help
description: Stuck with something? Get some help.
body:
- type: textarea
  attributes:
    label: What's the issue you're running into?
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    placeholder: |
        1. Do this thing...
        2. Then do that thing...
        3. And finally, do something else...
    validations:
      required: true
- type: textarea
  attributes:
    label: Environment
    placeholder: Please copy the output of `php please support:details`
  validations:
    required: true
