name: Test Suite

on:
  push:
  pull_request:

jobs:
  php_tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [7.4, 8.0]
        laravel: [8.*, 7.*, 6.*]
        statamic: [3.1.*]
        os: [ubuntu-latest]
        include:
          - laravel: 8.*
            testbench: 6.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 6.*
            testbench: 4.*

    name: ${{ matrix.php }} - ${{ matrix.statamic }} - ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v1

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "statamic/cms:${{ matrix.statamic }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer install --no-interaction

      - name: Run PHPUnit
        run: composer test
